develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35739:35729"
  environment:
    CT_URL: http://mymachine:9000 
    LOCAL_URL: http://mymachine:3005
    CT_TOKEN: null
  command: develop
  volumes:
    - ./app:/opt/i2i/app
  links: 
    - postgres
postgres:
  image: postgres:9.6
  environment: 
    POSTGRES_PASSWORD: root
    POSTGRES_USER: root
    POSTGRES_DB: i2i
  volumes:
    - ./database:/var/lib/postgresql/data

